steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/digital-ocean-demo', '.']

  # Run the Playwright tests using the Docker container
  - name: 'gcr.io/$PROJECT_ID/digital-ocean-demo'
    args: ['npm', 'run', 'test']
