steps:
# Remove existing image if any
- name: 'gcr.io/cloud-builders/docker'
  args: ['rmi', '-f', 'gcr.io/$PROJECT_ID/digital-ocean-demo']
  id: 'RemoveImage'

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/digital-ocean-demo02', '.']

# Push the Docker image to Google Container Registry (Optional)
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/digital-ocean-demo']

# Run the Playwright tests using the Docker container
- name: 'gcr.io/$PROJECT_ID/digital-ocean-demo02'
  args: ['npm', 'run', 'test']
